#'@name rcop
#'@title Simulation of a Gaussian Copula Distribution
#'@description NOTE: problematic treatment of duplicate values in Dens.y.
#'             Only seems to be a problem for highly skewed marginals, so far...
#'@param n An integer giving the number of rows to be generated
#'@param par paramaters generated by \code{cop.par}
#'@param dens.x used as a parameter to \code{cop.par} if par if missing
#'@param dens.y used as a parameter to \code{cop.par} if par if missing
#'@param Rho used as a parameter to \code{cop.par} if par if missing
#'@param mean used as a parameter to \code{cop.par} if par if missing
#'@param sd used as a parameter to \code{cop.par} if par if missing
#'@param debug a boolean (\code{FALSE} by default) if set to \code{TRUE}, will cause the function to open a browser mid-call
#'@return a matrix of size \code{n} x \code{length(dens.x)}
#'@export
rcop <- function(n, par, dens.x, dens.y, Rho, mean, sd, debug = FALSE) {
  if(missing(par)) par <- cop.par(dens = dens.x, dens.y = dens.y,
                                  Rho = Rho, mean = mean, sd = sd)
  dens.x <- par$dens.x
  dens.y <- par$dens.y
  ldens.y <- par$ldens.y
  Dens.y <- par$Dens.y
  Rho <- par$Rho
  mean <- par$mean
  sd <- par$sd
  dx <- par$dx
  rx <- par$rx
  nrv <- length(dens.x)
  ndens <- sapply(dens.x, length)
  if(debug) browser()
  # Simulate Uniforms
  P <- pnorm(rmvnorm(n, sigma = Rho))
  X <- matrix(NA, n, nrv)
  nm <- which.min(sapply(par, function(l) is.null(names(l))))
  colnames(X) <- names(par[[nm]])
  for(i in 1:nrv) {
    tmp <- c(0, Dens.y[[i]], 1)
    tmpi <- !duplicated(tmp)
    ind <- as.numeric(cut(P[,i], breaks = tmp[tmpi])) - 1
    iind <- pmax(pmin(ind, sum(tmpi)-3), 1)
    Dy <- diff(Dens.y[[i]][tmpi])[iind]
    PDy <- P[,i] - Dens.y[[i]][tmpi][iind]
    X[,i] <- ifelse(1 <= ind & ind <= sum(tmpi)-3,
                    dens.x[[i]][tmpi][iind] + (PDy/Dy - 1/2)*dx[i],
                    qnorm(P[,i], mean = mean[i], sd = sd[i]))
  }
  X
}
